# Generated by Django 4.2.7 on 2023-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
